### ISSUE TITLE
Mock responses when capturing http request

### ISSUE THREAD

**Issue by Miguelife** [AvdLee/RocketSimApp#602] opened 2024-10-23 12:04 UTC
**Is your feature request related to a problem? Please describe.**
I want to mock responses when using rocket sim to test my app functionality

**Describe the solution you'd like**
A similar approach to Proxyman to capture and mock responses
https://proxyman.io/

**Comment by AvdLee** [comment] 2024-10-24 06:48
Yes, great idea! Closing as a duplicate of #586, you can follow progress there.

**Closed by AvdLee** 2024-10-24 06:48 UTC
Labels: enhancement
