### ISSUE TITLE
Add support for screenshots to be in PNG format (so they can have a transparent background)

### ISSUE THREAD

**Issue by bevan667** [AvdLee/RocketSimApp#358] opened 2023-05-25 23:31 UTC
**Is your feature request related to a problem? Please describe.**
You can export a screenshot with bezels in JPG format only. I would like to have a screenshot with bezels with a transparent background so I can use the image in other ways.

**Describe the solution you'd like**
Please add (or change to) using PNG format for the screenshot images 

**Describe alternatives you've considered**
JPG doesn't have an alpha channel, so I am stuck

**Additional context**

**Comment by AvdLee** [comment] 2023-05-26 09:40
Duplicate of https://github.com/AvdLee/RocketSimApp/issues/329
And as [mentioned on Twitter](https://twitter.com/twannl/status/1661989428602994690?s=20):

> If you turn off App Store Connect optimization it should work. ASC does not accept png which is why the result becomes a JPEG 👌🏻

**Comment by AvdLee** [comment] 2023-05-26 09:41
Btw, this was covered in the FAQ section: 
![CleanShot 2023-05-26 at 11 41 02@2x](https://github.com/AvdLee/RocketSimApp/assets/4329185/797e85e1-8b56-47fb-985b-d0d9a693203e)

Out of interest, did you look at it at all? I might need to optimize both FAQ finding as well as making it more clear the format changes due to ASC optimization

**Closed by AvdLee** 2023-05-26 09:40 UTC
Labels: enhancement
