### ISSUE TITLE
App not starting

### ISSUE THREAD

**Issue by deivitaka** [AvdLee/RocketSimApp#563] opened 2024-08-08 10:02 UTC
**Describe the bug**
Suddenly I am not able to start the app

**To Reproduce**
Not known

**Expected behavior**
Launch app

**Screenshots**

**Desktop (please complete the following information):**
- MacBook Pro (M1 Pro)
 - OS: MacOS
 - Version: 14.5 (23F79)

**Additional context**
Tried reinstalling and restarting without success.
Able to run it from MacOS 15.0 Beta on the same machine (same installation)

[RocketSim-2024-08-08-112923.ips.txt](https://github.com/user-attachments/files/16541406/RocketSim-2024-08-08-112923.ips.txt)

**Comment by deivitaka** [comment] 2024-08-12 09:24
I am not sure what changed, but it now works again.

**Comment by deivitaka** [comment] 2024-09-13 13:51
I have to reopen this, I am not able to run the app for a few days, even with fresh installing the latest version 12.11.7.

[Archive.zip](https://github.com/user-attachments/files/16994791/Archive.zip)

**Comment by AvdLee** [comment] 2024-09-16 09:09
@deivitaka thank you so much for sharing these files. I've been able to symbolicate and indicate where things go wrong.
I'll work on a fix today and submit it asap.

Closing https://github.com/AvdLee/RocketSimApp/issues/573 as a duplicate of this.

**Comment by AvdLee** [comment] 2024-09-16 09:17
This will be fixed in 12.11.8

**Closed by AvdLee** 2024-09-16 09:17 UTC
Labels: bug
