### ISSUE TITLE
Screenshots and movies not being generated when using iOS 15.4 sims from Xcode 13.3 b1

### ISSUE THREAD

**Issue by markltownsend** [AvdLee/RocketSimApp#143] opened 2022-02-08 23:36 UTC
**Describe the bug**
When trying to create a screenshot using the iOS 15.4 simulator from Xcode 13.3b1 using the side panels, the panel comes up to generate the png file, but hangs there.

**To Reproduce**
1. Open iOS Simulator from Xcode 13.3b1
2. Click "Create Screenshot" on side panel next to simulator
3. Observe the "Creating PNG" panel showing with progress bar
4. Progress bar does not move and PNG is not saved or displayed as with previous versions of Xcode.

**Expected behavior**
Selecting "Create Screenshot" will show "Generating PNG" and then show a thumbnail of the screenshot and over options to copy or save the png.

**Desktop (please complete the following information):**
 - OS: macOS 12.2, Xcode 13.3b1, iOS Simulator 15.4.
 - Version RocketSim 6.0.4(87)

**Comment by AvdLee** [comment] 2022-02-09 09:49
Thanks for reporting in, I'll take a look!

**Comment by AvdLee** [comment] 2022-02-13 12:24
@markltownsend I could not reproduce this locally. Can you share a Diagnostics report through Preferences -> About - Report an Issue?

**Comment by markltownsend** [comment] 2022-02-14 17:21
@AvdLee Of course, I can't reproduce it either locally now.  The only difference before and now, is that I updated to macOS 12.2.1 which made my iPhone 13 simulators disappear for Xcode 13.3b2.  Recreating the simulator for iPhone 13 Pro with iOS 15.4, I was not able to reproduce.  

Is it possible that the issue was happening because of some issue with the iPhone 13 simulator itself that was causing the issue?

**Comment by AvdLee** [comment] 2022-02-15 12:36
> Is it possible that the issue was happening because of some issue with the iPhone 13 simulator itself that was causing the issue?

Very unlikely! I rather think this has something to do with the Xcode version being selected as command-line tool. If you like, you could still share the Diagnostics report, since it likely contains the session that failed before. It would potentially allow me to find the root cause.

**Comment by AvdLee** [comment] 2022-02-25 09:05
Closing this as can't reproduce

**Closed by AvdLee** 2022-02-25 09:05 UTC
Labels: bug, question
