### ISSUE TITLE
Free Trial Fails to Find Temporary License

### ISSUE THREAD

**Issue by mkaulfers** [AvdLee/RocketSimApp#372] opened 2023-06-28 15:52 UTC
**Describe the bug**
When launching RocketSim, after the initial setup (Permissions Granted), I am noticing that after a short period of time the app stops recognizing my subscription and disables many of the controls, then marks them with `(Pro)` to indicate it's a pro feature. I am on Day `1` of the trial.

**To Reproduce**
1. On a fresh install (Never had Rocket Sim on this Mac) install from App Store
2. Open XCode
3. Open Rocket Sim for the first time. 
4. Go through setup
5. Select a subscription, and start trial.
6. Open a simulator device
7. Run a build and launch on a different simulator
8. Make a few changes in RocketSim using it's `(Pro)` features
9. After a moment the controls will become disabled
10. It may disable while not in focus. 

**Expected behavior**
I expect to only have to go through the `Subscription` flow one time, when the app has it's initial setup completed. I shouldn't have to constantly hit the `Become Pro` either from settings, or from the context menu on the status bar icon. 

**Screenshots**
I just went through the subscription steps.
![Screenshot 2023-06-28 at 10 49 07 AM](https://github.com/AvdLee/RocketSimApp/assets/42121989/9722b8ea-8800-4cbb-a70f-09ccacd9dc65)

**Desktop (please complete the following information):**
 - OS: 13.4
 - XCode: 14.3.X
 - Simulator 16+
 - Apple Silicon Mac

**Additional context**
Not sure if there's any more context I can provide. Let me know if I can help in any way. I'd love to help RocketSim out on this one.

**Comment by mkaulfers** [comment] 2023-06-28 16:11
Here's a video of the issue as it happens. https://youtu.be/-Q5-3s1vbWA

**Comment by AvdLee** [comment] 2023-07-05 12:45
@mkaulfers thanks a lot for your report. Would you mind sharing a Diagnostics report via Settings -> About -> Report an issue?

In the video it looks like you didn't complete the restore cycle, since there's no expiry date visible as well. Can you confirm that's the case? 🤔

**Comment by mkaulfers** [comment] 2023-07-26 04:07
@AvdLee apologies for missing this. I'll see if I can get that for you.

**Comment by AvdLee** [comment] 2023-08-18 13:37
@mkaulfers I'm closing this issue for now as I'm cleaning up references. I would still love to have a look if you happen to reproduce this again with a Diagnostics report 🙏

**Closed by AvdLee** 2023-08-18 13:37 UTC
Labels: bug
