### ISSUE TITLE
Grid is not center aligned

### ISSUE THREAD

**Issue by awolf-foreflight** [AvdLee/RocketSimApp#509] opened 2024-05-07 23:35 UTC
**Describe the bug**
The grid overlay is not center aligned.   This results in what should be the centerline not being centered.

**To Reproduce**
1. Display screen with Navbar title in simulator
2. Turn on the RocketSIM grid

** Actual Behavior **
See screen shot.  The grid squares on the edges are not the same size.  This means the grid is not centered.  

**Expected behavior**
I'd like that thicker line that is near the horizontal center of the screen to be precisely in the center of the screen.  Resulting in a vertical gridline I could use to make sure my title is centered.

**Screenshots**
![CleanShot 2024-05-07 at 16 27 21](https://github.com/AvdLee/RocketSimApp/assets/131712912/a583c614-7e7f-4630-a729-83f7a9e082ee)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]. << Unclear to me what you want here.
 - Version: [e.g. 22]

This is on an iOS 17.2 simulator
RocketSim 12.6.2
Xcode 15.2
MacOS: Ventura 13.6.4

**Additional context**
Love the app, thanks for making it!  :)

**Comment by AvdLee** [comment] 2024-05-28 12:59
@awolf-foreflight yes, good point! This is a duplicate of #513. I'll see what I can do with that issue!

**Closed by AvdLee** 2024-05-28 12:59 UTC
Labels: bug
