### ISSUE TITLE
Ability to override iOS Simulator Date / Time

### ISSUE THREAD

**Issue by tareksabry1337** [AvdLee/RocketSimApp#348] opened 2023-05-01 15:50 UTC
Problem Statement:
Currently when developing it's not possible to override date / time of simulator apart from the system time, Which is really a stupid limitation and it enforces you to change your entire machine date / time which screws with other million things and this shouldn't be the only option to change the date

Solution Proposed:
With your recent solution to simulating Airplane mode I believe you'll be able to do the same for date / time simulation with the ability to change it only in one place

**Comment by AvdLee** [comment] 2023-05-01 18:07
Closing this as a duplicate of #332 which can't be build due to a bug in Xcode right now. TL;DR: It's on my radar!

**Closed by AvdLee** 2023-05-01 18:07 UTC
Labels: enhancement
