### ISSUE TITLE
Doesn't save

### ISSUE THREAD

**Issue by chriisong** [AvdLee/RocketSimApp#47] opened 2020-08-23 23:26 UTC
**Describe the bug**
Whether MP4 or GIF format, after recording the simulator and the little preview is shown at the bottom right of the screen, saving does not actually save to the designated folder.

**To Reproduce**
1. record
2. end record
3. file won't save

**Expected behavior**
file will save

**Desktop (please complete the following information):**
 - OS: 10.15.6
 - Version 2.2.1(31)

**Comment by AvdLee** [comment] 2020-08-24 06:45
@chriisong is the file being saved in a different folder instead? or isn't it saved at all?
If the latter, you could try changing the destination folder but it's obviously a bug that needs to be fixed.

**Comment by chriisong** [comment] 2020-08-25 07:41
> @chriisong is the file being saved in a different folder instead? or isn't it saved at all?
> If the latter, you could try changing the destination folder but it's obviously a bug that needs to be fixed.

It does save if I make a new folder and select it as the location. I'm trying to figure out what causes the selected location to stop working

**Comment by AvdLee** [comment] 2020-08-25 15:05
@chriisong that would be super useful to know, I'll see what I can do too. Let me know if you have any updates!

**Comment by AvdLee** [comment] 2020-10-18 13:23
@chriisong did you manage to find out the cause?

**Comment by chriisong** [comment] 2020-10-18 19:25
> @chriisong did you manage to find out the cause?

I have not. But it happens when the app crashes, and afterwards it won't save to that folder. Is there a way for me to send you logs?

**Comment by AvdLee** [comment] 2020-10-19 07:23
There is a way directly through the Console.app in which you can filter per app. However, I might be better of implementing https://github.com/WeTransfer/Diagnostics, after which you can update and share it super easily.

T.b.c.!

**Comment by AvdLee** [comment] 2020-11-17 17:10
I found out the cause of this issue. I was setting the wrong security scope! This is fixed in the upcoming update.

**Closed by AvdLee** 2020-11-17 17:10 UTC
Labels: bug
