### ISSUE TITLE
Add location by coordinates (Latitude, Longitude)

### ISSUE THREAD

**Issue by devmuaz** [AvdLee/RocketSimApp#439] opened 2023-11-23 00:58 UTC
**Is your feature request related to a problem? Please describe.**
Having my app tested with different locations is extremely important, and some coordinates don't have specific name to be looked up in the map, so the problem here is that there's no way I can just simply enter specific coordinates `(Latitude, Longitude)` and save it to be used later.

**Describe the solution you'd like**
Adding an optional text fields for the coordinates inputs in the location settings where the user has the ability to add a location would be a great option since it adds extra location customization setting to the `RocketSim App`.

**Comment by AvdLee** [comment] 2023-11-27 09:23
Closing this as a duplicate of https://github.com/AvdLee/RocketSimApp/issues/361
I fully see why this is valuable, so I'll try to get this on my backlog as soon as possible 🙏

**Closed by AvdLee** 2023-11-27 09:23 UTC
Labels: enhancement
