### ISSUE TITLE
Selecting a json file to use for App Action JSON syncing not functional

### ISSUE THREAD

**Issue by markltownsend** [AvdLee/RocketSimApp#399] opened 2023-08-27 23:44 UTC
**Describe the bug**
I had 3 different buckets of "deeplinks" in the App Actions preferences. I had set this up before push notifications and locations were added as well as having the bundle id specified for the deeplinks.

So, I selected each of the buckets and did a JSON Export. This seemed to work well.  I combined them all into one file with the proper JSON format of the exported JSON.

Now, with just the one bucket that represents the app, I try to import the new JSON file and the app in non responsive.

I select "JSON Syncing" dropdown and choose "Select..". This opens a Finder Open Dialog. When I go to choose the json file, the App freezes up and the "Open" button is still disabled. I can only 

**To Reproduce**
1. Go to `Settings`
2. Click on 'App Actions'
3. Click the `JSON Syncing` drop down and choose `Select..."
4. Observe the Finder Open Dialog
5. Select a previously exported JSON file
6. See how the Open button is not enabled and there is no response until ESC is pressed

**Expected behavior**
Selecting a valid JSON formatted file for the `App Action` feature should parse and import the given information into the panel

**Screenshots**
<img width="948" alt="Screenshot 2023-08-27 at 1 46 30 PM" src="https://github.com/AvdLee/RocketSimApp/assets/395903/51403bb9-4d49-4c6b-818b-55cb78fb3efb">

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Version 13.5

**Additional context**

**Comment by AvdLee** [comment] 2023-09-19 18:15
@markltownsend thanks for the report! I'll see what I can do 🙏

**Comment by AvdLee** [comment] 2024-01-19 12:31
@markltownsend it's been a while, sorry for that! I'm trying to fix this but having a hard time reproducing. Would it be possible to share your JSON file to support@rocketsim.app so I can validate and fix?

**Comment by AvdLee** [comment] 2024-01-24 12:35
Closing this for now since I can't reproduce.

**Closed by AvdLee** 2024-01-24 12:35 UTC
Labels: bug
