### ISSUE TITLE
High CPU usage after saving as a GIF

### ISSUE THREAD

**Issue by Ariandr** [AvdLee/RocketSimApp#88] opened 2021-02-24 11:30 UTC
**Describe the bug**
That's the second bug similar to https://github.com/AvdLee/RocketSimApp/issues/85

**To Reproduce**
1. Launch RocketSim v.3.4.2
2. Record video of any duration, e.g. 4 seconds
3. Stop recording
4. Switch from MP4 format to GIF in the small window
5. Save the final GIF

**Expected behavior**
After that, the app shouldn't utilize much of CPU. But it does utilize a full 1 core. About 99-100%.

**Screenshots**
<img width="589" alt="Screenshot at Feb 24 13-16-31" src="https://user-images.githubusercontent.com/13591333/108994089-09704980-76a4-11eb-8e07-d0db04c85791.png">
<img width="526" alt="Screenshot at Feb 24 13-22-38" src="https://user-images.githubusercontent.com/13591333/108994095-0b3a0d00-76a4-11eb-9c87-f0d672383f7c.png">
<img width="559" alt="Screenshot at Feb 24 13-26-45" src="https://user-images.githubusercontent.com/13591333/108994099-0b3a0d00-76a4-11eb-8959-e4ffc2db4d5f.png">

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.7, Xcode 12.4
 - Version RocketSim 3.4.2

**Additional context**
I reproduced it several times. Sometimes I couldn't reproduce it from the first try.

**Comment by AvdLee** [comment] 2021-02-26 08:04
@Ariandr thanks for reporting in again! Although it shouldn't hit 100% at all, do you know if it goes away after a while? It helps me debug this 🙂

**Comment by Ariandr** [comment] 2021-02-28 10:48
@AvdLee 
In this case it didn't go away after 20 minutes of being there, I specifically didn't close the app to check if it went away.

**Comment by AvdLee** [comment] 2021-03-06 09:32
Thanks again, I found the cause! It's fixed in the next release.

**Closed by AvdLee** 2021-03-06 09:32 UTC
Labels: bug
