### ISSUE TITLE
Input Coordinates for Custom Locations

### ISSUE THREAD

**Issue by willshelley** [AvdLee/RocketSimApp#385] opened 2023-08-06 18:02 UTC
Trying to add custom locations you have to know the place name, so would be useful to be able to store coordinates. 

Coordinate storage rather than just place name.

**Comment by AvdLee** [comment] 2023-08-14 18:42
This is a great idea and actually already logged! Closing as a duplicate of https://github.com/AvdLee/RocketSimApp/issues/361

Let me know if you disagree and I'll reopen 👌

**Closed by AvdLee** 2023-08-14 18:42 UTC
Labels: enhancement
