### ISSUE TITLE
RocketSim aggressively lags my computer

### ISSUE THREAD

**Issue by gormster** [AvdLee/RocketSimApp#115] opened 2021-09-29 04:59 UTC
**Describe the bug**
Whenever I launch my app in the simulator with RocketSim running, my entire computer freezes for about five to ten seconds. Everything, even the mouse cursor. This also happens when switching back to the simulator.

Also, clicking the RocketSim menu icon does not open the menu; I had to quit the app from Activity Monitor.

**To Reproduce**
1. Have RocketSim running
2. Launch an app in the simulator

… yeah, that's all I've got. I don't know what was causing it. Restarting RocketSim seemed to fix it, but like I said, I had to go to Activity Monitor to even be able to quit it. It's possible that it's something building up over time? I've had RocketSim running in the background for… probably two weeks? I'll see if it happens again, I guess.

**Expected behavior**
My system should not experience any slowdown as a result of using RocketSim.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6
 - Xcode 13.0 (13A233)
 - MacBook Air (M1, 2020) 16GB RAM
 - Version 5.1.0 (63)

**Comment by AvdLee** [comment] 2021-09-29 11:56
Thanks for reporting this! I've experienced this in the past too, but not recently anymore so I figured it was solved or just a debug build causing it. I'll see if I can find the cause.

Could it be that you've had cancelled conventions? I can imagine that I don't clean up those assets from memory nicely 🤔 

Either way, any extra context is welcome, but I'll see what I can do with what we've got today

**Comment by AvdLee** [comment] 2021-10-30 09:16
@gormster did it happen recently with the latest app version? I haven't experienced it myself lately anymore!

**Comment by AvdLee** [comment] 2021-11-30 20:31
I couldn't reproduce this anymore, so closing this

**Closed by AvdLee** 2021-11-30 20:31 UTC
Labels: bug
