### ISSUE TITLE
Manage iOS Status Bar

### ISSUE THREAD

**Issue by willshelley** [AvdLee/RocketSimApp#386] opened 2023-08-06 18:08 UTC
Have seen some examples where you can manage the status bar for screenshots, would be great if there's a standardised view of the status bar. Or using it to show low data or other scenarios.

Have had limited success with the below:
xcrun simctl status_bar "iPhone 14 Pro" override --time 9:41 --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --cellularBars 4 --batteryState charged --batteryLevel 100

Some way of manually changing the status bar state.

The above command is not working very well for me.

**Comment by AvdLee** [comment] 2023-08-14 18:47
Thanks for the report! This is a highly requested feature and a duplicate of https://github.com/AvdLee/RocketSimApp/issues/303

Unfortunately, this is not possible due to an Xcode Simulator bug:

![image](https://github.com/AvdLee/RocketSimApp/assets/4329185/603af100-865b-4b62-be46-6b9dc686a139)

I'd recommend subscribing to the linked issue for updates.

**Closed by AvdLee** 2023-08-14 18:47 UTC
Labels: enhancement
