### ISSUE TITLE
[11.0.0] Rulers aren't created/registered

### ISSUE THREAD

**Issue by efstathiosntonas** [AvdLee/RocketSimApp#378] opened 2023-07-27 08:35 UTC
**Describe the bug**
After upgrading to `11.0.0 (169)` I can't set rulers. See attached video.

I've quited simulator/rocketsim but it persists.

**Expected behavior**
Rulers should be created

**Desktop (please complete the following information):**
 - OS: Ventura 13.4.1

**Additional context**
Video demo:

https://github.com/AvdLee/RocketSimApp/assets/717975/c4511fa3-dfb4-4961-a5a7-685680e3ef80

**Comment by efstathiosntonas** [comment] 2023-07-27 08:40
It seems that after disabling rulers from Settings and re-enabling them it fixed it self. 

I'll leave the issue open if there's investigation needed otherwise please close it. Thanks

**Comment by AvdLee** [comment] 2023-07-27 09:19
@efstathiosntonas thanks for reporting in! I have an idea where this is coming from and I'll work on a fix tomorrow 💪

**Comment by efstathiosntonas** [comment] 2023-07-27 09:23
Thanks @AvdLee!

**Comment by AvdLee** [comment] 2023-07-28 06:23
This will be fixed in 11.1.0

**Comment by efstathiosntonas** [comment] 2023-07-28 06:34
Thanks @AvdLee, keep it up!

is there an ETA?

**Comment by AvdLee** [comment] 2023-07-31 11:58
@efstathiosntonas the build is already live in the App Store! Let me know if it didn't work for you 🙂

**Comment by efstathiosntonas** [comment] 2023-07-31 14:07
Hi @AvdLee, it works as a charm! Totally forgot to update the issue, thanks!

**Comment by efstathiosntonas** [comment] 2023-08-01 10:03
Hi @AvdLee , rulers are broken again on `11.2.0 (171)`

https://github.com/AvdLee/RocketSimApp/assets/717975/e647f236-7ffb-45f6-9883-f173ed17d731

**Comment by efstathiosntonas** [comment] 2023-08-01 10:04
@AvdLee it seems that it's broken if the Simulator is "Stay on Top" from Window -> Stay on Top, still a bug but now a crucial one 😄

**Comment by AvdLee** [comment] 2023-08-02 06:33
Interesting, I wonder whether this is 11.2.0 specific, but nevertheless, I'll reopen so I can pick it up soon!

**Comment by efstathiosntonas** [comment] 2023-08-02 06:35
Thanks @AvdLee! 

Probably this is a rare case, I believe 0 devs have the Stay on Top turned on, neither did you while developing it! 🤣

**Comment by AvdLee** [comment] 2023-08-02 06:44
You'll be surprised! 🤣 But nevertheless, I like to have main functionality work as expected, so it's worth checking to see if it's low hanging fruit!

**Comment by AvdLee** [comment] 2023-08-18 13:34
I was not able to reproduce this anymore, therefore, closing.

**Closed by AvdLee** 2023-08-18 13:34 UTC
Labels: bug
