### ISSUE TITLE
Screenshots no longer save as PNGs

### ISSUE THREAD

**Issue by vallette** [AvdLee/RocketSimApp#329] opened 2023-04-10 16:56 UTC
Screenshots now save as JPEGs instead of PNGs resulting in a solid white rather than transparent background greatly reducing their usefulness. All documentation (e.g., the website) still indicates screenshots are saved as PNGs. Is this a permanent change?

**Comment by FrankSolleveld** [comment] 2023-04-11 07:50
I also noticed this. Would love to see the option to save as PNG again! :)

**Comment by AvdLee** [comment] 2023-04-11 09:36
Duplicate of #325, simply disable App Store Connect optimization. ASC does not accept images with alpha layer which is why they result in JPEG output.

**Closed by AvdLee** 2023-04-11 09:36 UTC
