### ISSUE TITLE
Video saved by RocketSim isn't displayed in GitHub when viewed with Firefox

### ISSUE THREAD

**Issue by bsrz** [AvdLee/RocketSimApp#307] opened 2023-03-15 14:53 UTC
**Describe the bug**

The mp4 videos saved directly by RocketSim do not show up properly in GitHub pull request description using Firefox.

**To Reproduce**
1. Launch simulator
2. Click on 'MP4 Record'
3. Record your video
4. After processing is complete, click on 'Save'
5. Drag the saved mp4 into a GitHub pull request description
6. Preview the description or save it
7. Video displayed as blank

Processing the video with [Permute](https://software.charliemonroe.net/permute/) fixes the issue.

Note: both videos work in Safari

**Expected behavior**

The video should be displayed in the GitHub description in all browsers.

**Screenshots**

RocketSim video:

https://user-images.githubusercontent.com/1077441/225345062-331b5c53-34fe-4e4a-b721-763f8bb8eceb.mp4

Permute video:

https://user-images.githubusercontent.com/1077441/225346448-1ae74fa5-c929-41ea-b2a0-0d6e5f1aac53.mp4

**Desktop:**
 - RocketSim: 10.0.1 (142)
 - macOS: Ventura 13.2.1
 - Firefox: 110.0.1

**Comment by bsrz** [comment] 2023-03-15 14:55
Firefox screenshot:

![CleanShot000150](https://user-images.githubusercontent.com/1077441/225348699-01896aa0-e11b-4e99-94f6-bc187c99eba6.png)

Safari screenshot:

![CleanShot000151](https://user-images.githubusercontent.com/1077441/225348802-cbbf7de5-3702-418b-85d6-24a168f3f265.png)

**Comment by bsrz** [comment] 2023-03-16 14:51
@AvdLee here you go!

![CleanShot000152](https://user-images.githubusercontent.com/1077441/225655370-f83b64f3-ab5a-48a5-9669-16b26cfaeeba.png)

Let me know if you need anything else!

**Comment by AvdLee** [comment] 2023-03-18 12:44
@bsrz could you change the background color to e.g. #000000 without Alpha, and see if you can reproduce the issue? I think it's because the output video is a video with alpha and Permute removes that alpha layer

**Comment by bsrz** [comment] 2023-03-20 15:42
Direct from RocketSim without alpha:

https://user-images.githubusercontent.com/1077441/226392257-30df3a31-e254-4393-b29d-1d1a46f49615.mp4

**Comment by bsrz** [comment] 2023-03-20 15:43
@AvdLee that worked. Not sure what would be the fix for this... maybe a checkbox with "optimize for web/Firefox" or something?

**Comment by AvdLee** [comment] 2023-03-22 14:14
@bsrz I'm not sure if I can optimize for this, since I don't know the destination of the drag. I also can't catch drop failures in a browser.

I believe this is a general issue with any video that's dropped using alpha and the solution should be in browsers returning a descriptive failure "This video can't be used since it's containing an alpha layer".

I'm closing this issue for now at least, but let me know if you have other thoughts!

**Closed as not planned by AvdLee** 2023-03-22 14:14 UTC
Labels: bug
