### ISSUE TITLE
Icon in the menu bar is overlapped by numbers on a macbook 14 m1

### ISSUE THREAD

**Issue by hamza-imran75** [AvdLee/RocketSimApp#430] opened 2023-11-14 05:13 UTC
**Describe the bug**
When I opened Rocket Sim after awhile I realized that there were some numbers overlapping the Rocket Sim icon in the top bar(Where the battery icon and such things are in macOS), such a behavior hasn't happened before with any of the icons, so I believe it's a problem with Rocket sim.

**To Reproduce**
1. Open Rocket sim
2. Wait for numbers to appear in the top bar

**Expected behavior**
Numbers shouldn't be overlapping

**Screenshots**
<img width="114" alt="Screenshot 2023-11-14 at 10 06 49 AM" src="https://github.com/AvdLee/RocketSimApp/assets/43512631/b09fbb6b-0388-41cd-af75-c26608ecd933">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma Version 14.0 (23A344)
 - Rocket Version: 12.1.1 (187)

**Comment by AvdLee** [comment] 2023-11-15 13:56
@hamza-imran75 thanks for reporting! This is very strange and something I haven't seen before. Are you sure you're not using any other Mac apps that allow customization of the status bar? What happens if you restart your MacBook, does the issue still persist?

I'm not doing anything crazy with RocketSim's status bar icon, so I'm not sure what I can do 🤔

**Comment by hamza-imran75** [comment] 2023-11-15 13:59
Nope I'm not customising the appbar(didn't know this is possible 😅). Haven't restarted my Mac, will try to do it and let you know. Could it be related to the items in the status bar?

**Comment by AvdLee** [comment] 2023-11-16 14:14
> Could it be related to the items in the status bar?

Yes, definitely. It looks like there's some kind of time behind RocketSim's icon. Another thing you can try:
Hold cmd and drag the RocketSim icon to a different position. See if the background is still filled with the numbers

**Comment by AvdLee** [comment] 2024-02-28 19:33
Closing this as a duplicate of https://github.com/AvdLee/RocketSimApp/issues/437. Will fix it there!

**Closed by AvdLee** 2024-02-28 19:33 UTC
Labels: bug
