### ISSUE TITLE
Watch records duration is doubled

### ISSUE THREAD

**Issue by djavan-tagheuer** [AvdLee/RocketSimApp#86] opened 2021-02-19 09:24 UTC
**Describe the bug**
A video record of a watch simulator has a duration that is twice the real one

**To Reproduce**
1. Start a record of the Apple Watch simulator
2. Stop it after a minute
3. Save the video
4. Open the video
=> The video's duration is 2 minutes,

**Expected behavior**
You expect to see a one minute video.

**Desktop (please complete the following information):**
 - Version 3.4.1 (45)

**Comment by djavan-tagheuer** [comment] 2021-02-19 09:33
Little precisions
- in fact, after the normal duration we have the last frame for the whole duration
- does not apply to a 15s video

Here is an example of the video:

https://user-images.githubusercontent.com/43636702/108485998-daba3380-729d-11eb-8cf6-ccb3c9ce12b9.mp4

**Comment by AvdLee** [comment] 2021-02-21 15:27
@djavan-tagheuer thanks for reporting in. Can you try to see whether the same issue occurs when using:

`xcrun simctl io booted recordvideo test.mp4` 

From the terminal?

**Comment by AvdLee** [comment] 2021-03-06 12:19
Nevermind, found the cause. Will be fixed in the next release!

**Closed by AvdLee** 2021-03-06 12:19 UTC
Labels: bug

**Comment by djavan-tagheuer** [comment] 2021-04-22 16:40
Hey I'm really sorry I did not receive any notification about your request. 
But I can confirm it is fixed ! Thanks a lot ! 💪
