### ISSUE TITLE
RocketSim Pro

### ISSUE THREAD

**Issue by TheAbstractDev** [AvdLee/RocketSimApp#431] opened 2023-11-14 13:10 UTC
Hi !

First of all, thanks for this tool, it's really the best simulator add-on.

I just wanted to ask you if you can bring RocketSim to Setapp ?

It's a great alternative to the App Store and for people who already have a subscription it can be awesome.

Thanks

**Comment by AvdLee** [comment] 2023-11-15 13:53
Duplicate of #425. Unfortunately, there are no plans for bringing this app to Setapp.

**Closed by AvdLee** 2023-11-15 13:53 UTC

**Comment by TheAbstractDev** [comment] 2023-11-15 17:03
Oh .. why so ?

**Comment by AvdLee** [comment] 2023-11-27 09:19
My biggest reason is that I don't want to maintain two App Stores. Secondly, friends have tried it out and found it not worth the investment in terms of returns. Since RocketSim is a side project, I have to pick my battles 🙏
