### ISSUE TITLE
Store user login data (email and pass) like we have option to store locations

### ISSUE THREAD

**Issue by lazar-urbansportsclub** [AvdLee/RocketSimApp#591] opened 2024-10-09 07:24 UTC
**Is your feature request related to a problem? Please describe.**
Would it be possible to add section where we can store few users with information like email and pass that we use for testing. I always have multiple users that i login and logout while i do development so would be nice if we could have section like for location where we would be able to create users and when needed we could press on it to populate active text field with data. We press on email field press on button (or shortcut)  and it enters text for us.

**Describe the solution you'd like**
I would like to populate text field value with value of selected user. It can be either username or password. Would be nice if we could detect if field is secure or not and if its secure it automatically copy value of password and if not then it copies value of email.

**Describe alternatives you've considered**
Right now i am using text files with data for user logins or i add some test code like long press on some element to populate my data but i would like to do it without adding any code.

**Additional context**
Great extension. Keep up the great work!

**Comment by AvdLee** [comment] 2024-10-24 06:53
Closing as a duplicate of #347. 

That's good news for you @lazar-urbansportsclub. Even better: I have a local prototype working which I'll likely finalize in Q1 2025!

**Closed by AvdLee** 2024-10-24 06:53 UTC
Labels: enhancement
